apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
  namespace: argocdk8s
spec:
  selector:
    app: todo-ui
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer

...
apiVersion: v1
kind: Service
metadata:
  name: todo-backend
  namespace: argocdk8s
spec:
  selector:
    appg: todo-get
    appd: todo-delete
    appa: todo-add
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer